/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewUser;

import view.*;
import TabelKebersihan.cleanView;
import TabelPenghuni.daftarView;
import config.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class MenuViewUser extends javax.swing.JFrame {
    
    public MenuViewUser() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
      
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_panel = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JButton();
        btnDaftarKebersihan = new javax.swing.JButton();
        btnTentang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        beranda_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        daftarkebersihan_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_nokamarK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kebersihan = new javax.swing.JTable();
        btn_hapusK = new javax.swing.JButton();
        btn_tambahK = new javax.swing.JButton();
        btn_cariKebersihan = new javax.swing.JButton();
        txt_cariKebersihan = new javax.swing.JTextField();
        tentang_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        header_panel = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        body_panel.setBackground(new java.awt.Color(21, 87, 79));

        menu_panel.setBackground(new java.awt.Color(21, 87, 79));
        menu_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnBeranda.setBackground(new java.awt.Color(255, 255, 255));
        btnBeranda.setText("BERANDA");
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        btnDaftarKebersihan.setBackground(new java.awt.Color(255, 255, 255));
        btnDaftarKebersihan.setText("DAFTAR KEBERSIHAN");
        btnDaftarKebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarKebersihanActionPerformed(evt);
            }
        });

        btnTentang.setBackground(new java.awt.Color(255, 255, 255));
        btnTentang.setText("TENTANG");
        btnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentangActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/house(128).png"))); // NOI18N

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDaftarKebersihan, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btnTentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDaftarKebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_panel.setBackground(new java.awt.Color(21, 87, 79));
        main_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        main_panel.setPreferredSize(new java.awt.Dimension(805, 501));
        main_panel.setLayout(new java.awt.CardLayout());

        beranda_panel.setBackground(new java.awt.Color(255, 255, 255));
        beranda_panel.setPreferredSize(new java.awt.Dimension(805, 501));

        jLabel3.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        jLabel3.setText("Selamat Datang Di Hunian Kami");

        jLabel8.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel8.setText("Sixer's Kost");

        jLabel9.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        jLabel9.setText("Jl. Bangbayang No.23, Dago, Coblong, Bandung City, West Java 40135");

        javax.swing.GroupLayout beranda_panelLayout = new javax.swing.GroupLayout(beranda_panel);
        beranda_panel.setLayout(beranda_panelLayout);
        beranda_panelLayout.setHorizontalGroup(
            beranda_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beranda_panelLayout.createSequentialGroup()
                .addGroup(beranda_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(beranda_panelLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel8))
                    .addGroup(beranda_panelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel9))
                    .addGroup(beranda_panelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        beranda_panelLayout.setVerticalGroup(
            beranda_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beranda_panelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(98, 98, 98)
                .addComponent(jLabel9)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        main_panel.add(beranda_panel, "card2");

        daftarkebersihan_panel.setBackground(new java.awt.Color(255, 255, 255));
        daftarkebersihan_panel.setPreferredSize(new java.awt.Dimension(805, 501));

        jLabel5.setText("No Kamar");

        tbl_kebersihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kebersihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kebersihanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kebersihan);

        btn_hapusK.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapusK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        btn_hapusK.setText("HAPUS");
        btn_hapusK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusKActionPerformed(evt);
            }
        });

        btn_tambahK.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambahK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tambah (1).png"))); // NOI18N
        btn_tambahK.setText("TAMBAH");
        btn_tambahK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahKActionPerformed(evt);
            }
        });

        btn_cariKebersihan.setBackground(new java.awt.Color(255, 255, 255));
        btn_cariKebersihan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btn_cariKebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariKebersihanActionPerformed(evt);
            }
        });

        txt_cariKebersihan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_cariKebersihan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cariKebersihan.setText("Cari Berdasarkan No Kamar");
        txt_cariKebersihan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariKebersihanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariKebersihanFocusLost(evt);
            }
        });
        txt_cariKebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariKebersihanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daftarkebersihan_panelLayout = new javax.swing.GroupLayout(daftarkebersihan_panel);
        daftarkebersihan_panel.setLayout(daftarkebersihan_panelLayout);
        daftarkebersihan_panelLayout.setHorizontalGroup(
            daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftarkebersihan_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nokamarK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftarkebersihan_panelLayout.createSequentialGroup()
                        .addComponent(btn_cariKebersihan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cariKebersihan)
                        .addGap(186, 186, 186)
                        .addComponent(btn_tambahK)
                        .addGap(28, 28, 28)
                        .addComponent(btn_hapusK))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        daftarkebersihan_panelLayout.setVerticalGroup(
            daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarkebersihan_panelLayout.createSequentialGroup()
                .addGroup(daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daftarkebersihan_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nokamarK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(daftarkebersihan_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daftarkebersihan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapusK)
                        .addComponent(btn_tambahK))
                    .addComponent(btn_cariKebersihan)
                    .addComponent(txt_cariKebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        main_panel.add(daftarkebersihan_panel, "card4");

        tentang_panel.setPreferredSize(new java.awt.Dimension(805, 501));

        jLabel6.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 87, 79));
        jLabel6.setText("Tentang Aplikasi");

        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 87, 79));
        jLabel4.setText("Aplikasi ini dibuat untuk membantu penjaga kost ");

        jLabel10.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(21, 87, 79));
        jLabel10.setText("mendata penghuni kost yang akan dibersihkan kamarnya.");

        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(21, 87, 79));
        jLabel11.setText("Aplikasi Ini Dibuat Oleh SIXER'S TEAM :");

        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(21, 87, 79));
        jLabel12.setText("Rizki Maulana M. N (10118012)");

        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(21, 87, 79));
        jLabel13.setText("Surya Fakhriy Hasbi (10118028)");

        jLabel14.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(21, 87, 79));
        jLabel14.setText("Azis Komara (10118029)");

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(21, 87, 79));
        jLabel15.setText("Versi :");

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(21, 87, 79));
        jLabel16.setText("1.1.1");

        javax.swing.GroupLayout tentang_panelLayout = new javax.swing.GroupLayout(tentang_panel);
        tentang_panel.setLayout(tentang_panelLayout);
        tentang_panelLayout.setHorizontalGroup(
            tentang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentang_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tentang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        tentang_panelLayout.setVerticalGroup(
            tentang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentang_panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(77, 77, 77)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        main_panel.add(tentang_panel, "card5");

        header_panel.setBackground(new java.awt.Color(21, 87, 79));
        header_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnKeluar.setBackground(new java.awt.Color(21, 87, 79));
        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btnKeluar.setText("LOGOUT");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sixser's");

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kost");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout body_panelLayout = new javax.swing.GroupLayout(body_panel);
        body_panel.setLayout(body_panelLayout);
        body_panelLayout.setHorizontalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        body_panelLayout.setVerticalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_panelLayout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        
       //remove all panel
       main_panel.removeAll();
       main_panel.repaint();
       main_panel.revalidate();
       
       //add panel
       main_panel.add(beranda_panel);
       main_panel.revalidate();
    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        LoginView LV = new LoginView();
        
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Anda Yakin Ingin Keluar","Peringatan",dialogBtn);
        
        if (dialogResult == 0) {
            //true condition
            this.setVisible(false);
            LV.setVisible(true);   
        } else {
            //false condition
        }
        
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnDaftarKebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarKebersihanActionPerformed
        // TODO add your handling code here:
        //remove all panel
      cleanView cV = new cleanView();
      cV.setVisible(true);
    }//GEN-LAST:event_btnDaftarKebersihanActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        // TODO add your handling code here:
        //remove all panel
       main_panel.removeAll();
       main_panel.repaint();
       main_panel.revalidate();
       
       //add panel
       main_panel.add(tentang_panel);
       main_panel.revalidate();
    }//GEN-LAST:event_btnTentangActionPerformed

    private void btn_hapusKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusKActionPerformed
      
    }//GEN-LAST:event_btn_hapusKActionPerformed
       
    private void txt_cariKebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariKebersihanActionPerformed
      
        
    }//GEN-LAST:event_txt_cariKebersihanActionPerformed

    private void txt_cariKebersihanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariKebersihanFocusGained
       
    }//GEN-LAST:event_txt_cariKebersihanFocusGained

    private void txt_cariKebersihanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariKebersihanFocusLost
        
    }//GEN-LAST:event_txt_cariKebersihanFocusLost

    private void btn_tambahKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahKActionPerformed
        
    }//GEN-LAST:event_btn_tambahKActionPerformed

    private void tbl_kebersihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kebersihanMouseClicked
      
    }//GEN-LAST:event_tbl_kebersihanMouseClicked

    private void btn_cariKebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariKebersihanActionPerformed
     
       
        
    }//GEN-LAST:event_btn_cariKebersihanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuViewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beranda_panel;
    private javax.swing.JPanel body_panel;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnDaftarKebersihan;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTentang;
    private javax.swing.JButton btn_cariKebersihan;
    private javax.swing.JButton btn_hapusK;
    private javax.swing.JButton btn_tambahK;
    private javax.swing.JPanel daftarkebersihan_panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JTable tbl_kebersihan;
    private javax.swing.JPanel tentang_panel;
    private javax.swing.JTextField txt_cariKebersihan;
    private javax.swing.JTextField txt_nokamarK;
    // End of variables declaration//GEN-END:variables
}
